site: Casa dos Nerds
title: Um blog de nerd para nerds!
greetings: Bem vindo à Casa dos Nerds! 🖖
description: >-
  Um blog de nerd para nerds
lang: pt-BR 
timezone:  America/Sao_Paulo
repo: https://github.com/casadosnerds/blog # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: powex # replace with your disqus shortname
comments-enabled: true # true to enable disqus comments, false to hide them

author:
  name: Huvuptvbz
  bio: Apenas um amante de tecnologia!
  userpicture: 
  username: Huvuptvbz # general username
  github: casadosnerds # github username
  twitter: teste # twitter username
  mastodon: teste # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  email: almeida_pm@disroot.org # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "casadosnerds.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "/blog" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


