collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
  collection_pages:
    path: _pages
    name: Collection Pages
    icon: collections
  drafts:
    path: _drafts
    name: Drafts
    icon: event
    create:
      path: ''
      publish_to: posts
    _inputs:
      categories:
        type: multiselect
        options:
          values: collections.posts[*].categories
          allow_create: true
      tags:
        type: multiselect
        options:
          values: collections.posts[*].tags
          allow_create: true
  posts:
    path: _posts
    name: Posts
    icon: event_available
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    _inputs:
      categories:
        type: multiselect
        options:
          values: collections.posts[*].categories
          allow_create: true
      tags:
        type: multiselect
        options:
          values: collections.posts[*].tags
          allow_create: true
    add_options:
      - name: Add Post
      - name: Add Draft
        collection: drafts
paths:
  static: ''
  uploads: uploads
timezone: America/Sao_Paulo
markdown:
  engine: kramdown
  options:
    heading_ids: false
    gfm: true
    breaks: false
    typographer: true
    attributes: true
    attribute_elements:
      inline: right
      block: below
      tr: none
      td: none
      li: right-of-prefix
    treat_indentation_as_code: true
_snippets_imports:
  jekyll: true
